export const Settings={
    dots:false,
    Infinite:true,
    speed:500,
    slidesToShow:6,
    slidesToScroll:3,

    responsive:[
        {
            breakpoint:1500,
            settings:{
                dots:true,
                Infinite:true,
                slidesToShow:5,
                slidesToScroll:4,
            }
        },
        {
            breakpoint:1300,
            settings:{
                dots:true,
                Infinite:true,
                slidesToShow:4,
                slidesToScroll:3,
            }
        },
        {
            breakpoint:1024,
            settings:{
                dots:true,
                Infinite:true,
                slidesToShow:3,
                slidesToScroll:3,
            }
        },
        {
            breakpoint:600,
            settings:{
                slidesToShow:2,
                slidesToScroll:2,
                initialSlide:2
            }
        },
        {
            breakpoint:480,
            settings:{
                slidesToShow:1,
                slidesToScroll:1,
            }
        }
    ]
}